### ISSUE TITLE
Обучение

### ISSUE THREAD

**Issue by TorinAsakura** [atls-academy/lab-crossroads-neurolink#4]
На основе собранных данных обучи нейросеть, подавая на вход состояние светофоров и ожидая на выходе "состояние прогресса" каждого автомобиля. 

По мере обучения, нейросеть должна улучшать свои прогнозы и корректировать ошибки через обратное распространение.

**Comment by ghost** [comment]
Тут наверно не получится сходу сделать. Лучше на вход сети подавать матрицу дорог на которых есть/нет автомобили, на выходе получать матрицу светофоров. Матрицу светофором прогонять через модель и находить светофоры, которые отработали неправильно. Между предсказанной и скорректированной матрицами находить ошибку и делать обратное распространение

**Comment by TorinAsakura** [comment]
@mascas2 Принял во внимание, немного изменю метод обучения
